import assert from 'node:assert/strict';
import { test } from 'node:test';
import { readFileSync } from 'node:fs';
import { createHmac } from 'node:crypto';
import { decodeJwt, decodeProtectedHeader, SignJWT } from 'jose';
import { createJwt } from '@ireves/common-api';

const secret = 'migration-test-secret-at-least-32-bytes';
const auth = createJwt(() => secret);

test('jose accepts a token generated by jsonwebtoken 9.0.3', async () => {
  const fixture = JSON.parse(readFileSync(new URL('./jwt-legacy.json', import.meta.url), 'utf8'));
  const legacy = createJwt(() => fixture.secret);
  assert.deepEqual(await legacy.verifyJwt(fixture.token, { issuer: 'legacy-issuer', audience: 'legacy-api' }), fixture.payload);
  await assert.rejects(legacy.verifyJwt(fixture.token, { audience: 'other-api' }), { code: 'ERR_JWT_CLAIM_VALIDATION_FAILED' });
});

test('signing preserves HS256 format, defaults, claim options and caller values', async () => {
  const payload = Object.freeze({ custom: 'value', type: 'refresh' });
  const options = Object.freeze({ issuer: 'issuer', audience: 'api', subject: 'user', jwtid: 'id' });
  const token = await auth.createAccessToken(payload, options);
  const claims = await auth.verifyJwt(token, { issuer: 'issuer', audience: 'api', subject: 'user' });
  assert.deepEqual(decodeProtectedHeader(token), { alg: 'HS256', typ: 'JWT' });
  assert.equal(claims.type, 'access');
  assert.equal(claims.exp - claims.iat, 600);
  assert.equal(claims.jti, 'id');
  assert.equal(payload.type, 'refresh');
  assert.equal(options.algorithm, undefined);
  const [header, body, signature] = token.split('.');
  assert.equal(signature, createHmac('sha256', secret).update(`${header}.${body}`).digest('base64url'));
  const refresh = await auth.verifyJwt(await auth.createRefreshToken({}));
  assert.equal(refresh.type, 'refresh');
  assert.equal(refresh.exp - refresh.iat, 21600);
});

test('expiry is relative to iat, zero expires immediately, and nbf is enforced', async () => {
  const issuedAt = Math.floor(Date.now() / 1000) - 60;
  const token = await auth.createAccessToken({ iat: issuedAt }, { expiresIn: '2m' });
  assert.equal(decodeJwt(token).exp, issuedAt + 120);
  await assert.rejects(auth.verifyJwt(await auth.createAccessToken({}, { expiresIn: 0 })), { code: 'ERR_JWT_EXPIRED' });
  await assert.rejects(auth.verifyJwt(await auth.createAccessToken({}, { notBefore: '1h' })), { code: 'ERR_JWT_CLAIM_VALIDATION_FAILED' });
  const noTimestamp = decodeJwt(await auth.createAccessToken({}, { noTimestamp: true, expiresIn: 60 }));
  assert.equal(noTimestamp.iat, undefined);
  assert.equal(typeof noTimestamp.exp, 'number');
});

test('algorithm confusion, wrong keys and altered signatures are rejected', async () => {
  const wrongAlgorithm = await new SignJWT({ type: 'access' }).setProtectedHeader({ alg: 'HS384' })
    .sign(new TextEncoder().encode(secret));
  await assert.rejects(auth.verifyJwt(wrongAlgorithm), { code: 'ERR_JOSE_ALG_NOT_ALLOWED' });
  await assert.rejects(auth.verifyJwt(wrongAlgorithm, { algorithms: ['HS384'] }), { code: 'ERR_JOSE_ALG_NOT_ALLOWED' });
  const token = await auth.createAccessToken({});
  await assert.rejects(createJwt(() => 'different-secret').verifyJwt(token), { code: 'ERR_JWS_SIGNATURE_VERIFICATION_FAILED' });
  const [header, body, signature] = token.split('.');
  const changed = (signature[0] === 'a' ? 'b' : 'a') + signature.slice(1);
  await assert.rejects(auth.verifyJwt(`${header}.${body}.${changed}`), { code: 'ERR_JWS_SIGNATURE_VERIFICATION_FAILED' });
});

test('unsupported options, ambiguous durations and conflicting claims fail explicitly', async () => {
  for (const options of [{ algorithm: 'none' }, { mutatePayload: true }, { expiresIn: '120' }, { expiresIn: Infinity }]) {
    await assert.rejects(auth.createAccessToken({}, options), TypeError);
  }
  await assert.rejects(auth.createAccessToken({ exp: 4102444800 }, { expiresIn: '1h' }), /either payload or options/);
  await assert.rejects(auth.createAccessToken({ exp: 'invalid' }), /finite number/);
});
